/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class interfaces_can_Can */

#ifndef _Included_interfaces_can_Can
#define _Included_interfaces_can_Can
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     interfaces_can_Can
 * Method:    read
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_interfaces_can_Can_read
  (JNIEnv *, jclass);

/*
 * Class:     interfaces_can_Can
 * Method:    open_port
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_interfaces_can_Can_open_1port
  (JNIEnv *, jclass, jstring);

/*
 * Class:     interfaces_can_Can
 * Method:    send_port
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_interfaces_can_Can_send_1port
  (JNIEnv *, jclass);

/*
 * Class:     interfaces_can_Can
 * Method:    read_port
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_interfaces_can_Can_read_1port
  (JNIEnv *, jclass);

/*
 * Class:     interfaces_can_Can
 * Method:    close_port
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_interfaces_can_Can_close_1port
  (JNIEnv *, jclass);

/*
 * Class:     interfaces_can_Can
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_interfaces_can_Can_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
