/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Can */

#ifndef _Included_Can
#define _Included_Can
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Can
 * Method:    read
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Can_read
  (JNIEnv *, jobject);

/*
 * Class:     Can
 * Method:    open_port
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Can_open_1port
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Can
 * Method:    send_port
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Can_send_1port
  (JNIEnv *, jobject);

/*
 * Class:     Can
 * Method:    read_port
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Can_read_1port
  (JNIEnv *, jobject);

/*
 * Class:     Can
 * Method:    close_port
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Can_close_1port
  (JNIEnv *, jobject);

/*
 * Class:     Can
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Can_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
