/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Can */

#ifndef _Included_Can
#define _Included_Can
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Can
 * Method:    read
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Can_read
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
