INSERT INTO SensorLabels (tag, address, offset, byteLength, description, system, units, store, correction) VALUES
('PCT1AVG', '0', '0', '0', 'Pack 1 Average Cell Temp', 'TSV', 'C', '1', '1'),
('PCT2AVG', '0', '0', '0', 'Pack 2 Average Cell Temp', 'TSV', 'C', '1', '1'),
('PCT3AVG', '0', '0', '0', 'Pack 3 Average Cell Temp', 'TSV', 'C', '1', '1'),
('PCT4AVG', '0', '0', '0', 'Pack 4 Average Cell Temp', 'TSV', 'C', '1', '1'),
('PCV1AVG', '0', '0', '0', 'Pack 1 Average Cell Voltage', 'TSV', 'V', '1', '1'),
('PCV2AVG', '0', '0', '0', 'Pack 2 Average Cell Voltage', 'TSV', 'V', '1', '1'),
('PCV3AVG', '0', '0', '0', 'Pack 3 Average Cell Voltage', 'TSV', 'V', '1', '1'),
('PCV4AVG', '0', '0', '0', 'Pack 4 Average Cell Voltage', 'TSV', 'V', '1', '1')